export const elements = {
  feedback: document.querySelector('.feedback'),
  selectFeedback: document.querySelector('.select-feedback'),
  startDate: document.getElementById('start-date-search'),
  loader: document.querySelector('.loader-container'),
  endDate: document.getElementById('end-date-search'),
  dateForm: document.getElementById('asteroid-date'),
  asteroidList: document.querySelector('.asteroid-list'),
  table: document.querySelector('.asteroid-table'),
  tableBody: document.querySelector('.asteroid-info'),
  selectBox: document.getElementById('asteroids'),
  selectOption: document.querySelectorAll('.option-element'),
  nodeListItem: document.querySelectorAll('.list-item'),
  tableList: document.querySelector('.asteroid-info'),
  prevButton: document.getElementById('button-prev'),
  nextButton: document.getElementById('button-next'),
  asteroidsOption: document.getElementById('asteroids'),
  pageNumber: document.querySelector('.page-number'),
  chartContainer: document.querySelector('.chart-container'),
  loaderContainer: document.querySelector('.loader-container'),
};
